---
################## aerospike ###############
aerospike::version: 3.10.1
aerospike::download_user: 'myuser'
aerospike::download_pass: 'mypassword'
aerospike::amc_install: true
aerospike::amc_version: 3.6.13
aerospike::amc_download_url: 'http://www.aerospike.com/artifacts/aerospike-amc-community/3.6.13/aerospike-amc-community-3.6.13-el6.x86_64.rpm'
aerospike::amc_manage_service: true
aerospike::config_service:
  'paxos-single-replica-limit': 1
  'pidfile': '/var/run/aerospike/asd.pid'
  'service-threads': 4
  'transaction-queues': 4
  'transaction-threads-per-queue': 4
  'proto-fd-max': 15000
aerospike::config_net_hb:
  'mode': 'mesh'
  'port': 3002,
  'interval': 150
  'timeout': 10
aerospike::config_ns:
  'mobiadz':
    'replication-factor': 2
    'memory-size': '4G'
    'default-ttl': '60d'
    'storage-engine memory': ''
