nginx::nginx_vhosts:
  'mobiadz.themobiadz.com':
    proxy: '$upstream_frontend'
    proxy_set_header:
      - 'X-TenantId "mobiadz"'
      - 'X-Real-IP $remote_addr'
      - 'X-Forwarded-For $proxy_add_x_forwarded_for'
      - 'real_ip_header X-Forwarded-For'
      - 'set_real_ip_from 0.0.0.0/0'
    server_name:
      - "mobiadz.themobiadz.com"
    resolver:
      - "17.0.0.2 valid=3s"
    raw_prepend:
      - "set $upstream_backend \"http://frontend-asg.internal.adtech.com\";"
      - "set $upstream_frontend \"http://backend-asg-deployer.internal.adtech.com\";"
  'mobiadz.mbttk.net':
    proxy: '$upstream_adserver'
    proxy_set_header:
      - 'X-TenantId "mobiadz"'
      - 'X-Real-IP $remote_addr'
      - 'X-Forwarded-For $proxy_add_x_forwarded_for'
      - 'real_ip_header X-Forwarded-For'
      - 'set_real_ip_from 0.0.0.0/0'
    server_name:
      - "mobiadz.mbttk.net"
    resolver:
      - "17.0.0.2 valid=3s"
    raw_prepend:
      - "set $upstream_adserver \"http://adserver-asg-deployer.internal.adtech.com\";"
nginx::nginx_locations:
  'mobiadz.themobiadz.com':
    location: '/api/'
    vhost: 'mobiadz.themobiadz.com'
    proxy: '$upstream_backend'
    proxy_set_header:
      - 'X-TenantId "mobiadz"'
      - 'X-Real-IP $remote_addr'
      - 'X-Forwarded-For $proxy_add_x_forwarded_for'
      - 'real_ip_header X-Forwarded-For'
      - 'set_real_ip_from 0.0.0.0/0'
