---
apache::mpm_module: 'prefork'
apache::default_vhost: false
zabbix::zabbix_version: '3.2'
zabbix::zabbix_url: "%{::ipaddress_eth0}"
zabbix::zabbix_server: 'zabbix-node-1.internal.adtech.com'
zabbix::javagateway: "%{::ipaddress_eth0}"
zabbix::zabbix_timezone: 'UTC'
zabbix::javagatewayport: 10052
zabbix::startjavapollers: 16
zabbix::database_type: 'mysql'
zabbix::javagateway::listenip: "0.0.0.0"
zabbix::javagateway::startpollers: 16
